package PedroFernandes.NSS;

public class Enum {

    public enum INTERFACE{
        G, ATMPRESSURE, TEMP, INDEXREFRACTION, WAVELENGTHR, WAVELENGTHG, WAVELENGTHB, CAMMODE, EXPOSURE, STEPS, LIGHTSTEPS, SAMPLING, YEAR, MONTH, DAY, DECIMALTIME, LATITUDE, LONGITUDE, MERIDIAN, MINSTAR, MAXSTAR, CONSTELATION
    }
}
